import { StyleSheet } from 'react-native';

export const CourseStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  courseContainer: {
    flex: 1,
    alignItems: 'center',
    padding: 20,
    display: 'flex',

  },
  title: {
    flex: 1, 
    fontSize: 24,
    fontWeight: 'bold',
  },
  
  loader: {
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center',
    color: '#5F2DED',

  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    height: 50,
    marginBottom: 40,
    marginTop: 10,
    width: '100%',
    display: 'flex',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: 'transparent',
  },
  activeTab: {
    borderColor: '#F2277E',
  },
  tabText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
  },
  weekContainer: {
    width: '100%',
    marginVertical: 20,
    backgroundColor: '#5F2DED',
    borderRadius: 8,
    overflow: 'hidden',
  },
  weekHeader: {
    padding: 15,
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderColor: '#5F2DED',
    alignItems: 'center',
    display: 'flex',
  },
  weekText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 10,
  },
  lessonContainer: {
    padding: 15,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderColor: '#5F2DED',
    display: 'flex',
  },
  lessonItem: {
    marginBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center'
  },
  lessonText: {
    fontSize: 18,
    fontWeight: 'bold',
    display: 'flex',
    position: 'relative',
    right: 10,
    color: '#000',
    transform: [{ rotate: '-90deg' }], 

},
  contentContainer:{
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 8,
    display: 'flex',
    justifyContent: 'space-between',
  },
  contentText: {
    fontSize: 16,
    color: '#000',
    marginLeft: 10,
  },

  lectureBtn:{
    width: 250, 
    height: 50,  
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: 4,
    paddingHorizontal: 10,
    backgroundColor: 'transparent',
  },
  contentWrapper: {
    borderWidth: 1,
    borderColor: '0 0 1px 1px rgba(95, 45, 237, 0.2)',
    padding: 10,
    marginBottom: 8,
    borderRadius: 8,
    backgroundColor: '#F0F0F5',
  },
  completeButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    display: 'flex',
    backgroundColor: 'transparent',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    width: 30,
    height: 30,
    borderWidth: 2,
  },
  completedIconWrapper: {
    borderWidth: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4FD',
    width: 30,
    borderRadius: 30,
    height: 30,
    borderColor: '#46BD84',
  },
  checked:{
    color: '#46BD84'
  },
  backBtn:{
    position: 'relative', 
    width: 150,
    height: 40,
    marginBottom: 10,
    borderWidth: 2,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#5F2DED',
    borderRadius: 20,
    marginLeft: 10,
  },
});
